### ISSUE TITLE
Remove test folder

### ISSUE THREAD

**Issue by f3fora** [andersevenrud/nordic.nvim#21]
`test` and `Makefile` are useless for a colorscheme and we actually do not use that function anymore.

**Comment by andersevenrud** [comment]
Yeah. In the current state these don't really do much. I'm not sure if tests are completely useless for colorschemes, but since this one uses colorbuddy, there's less reason to do (even though there are some custom settings here, but pretty basic).

I've opened a PR to remove these in case @maaslalani also agrees :)

**Comment by maaslalani** [comment]
It makes sense to remove these, good call!
